# Generated by Django 4.1.7 on 2023-04-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_antique_description_antique_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antique',
            name='description',
            field=models.TextField(default='No description available.', max_length=250),
        ),
        migrations.AlterField(
            model_name='antique',
            name='material',
            field=models.CharField(default='Unknown', max_length=75),
        ),
    ]
